### PR TITLE
MSEDO-220/MSEDO-272/MSEDO-273/MSEDO-274: Add feedback and Active substance entities, and fields limits

### PR DESCRIPTION
**Pull request by DanielFran**
This PR includes the following changes:

- Switched to last NodeJs LTS version 14.15.x
- Update Angular version to 11 and other dependencies
- Javascript unit tests are now closer to the code in conformity with Angular best practices
- Vendor css do not overwrite Global css
- Define maximum length for fields in the database
- Add Feedback entity
- Change drug relation with notice to one-to-many
- Change symptom relation with toxicity-rate to one-to-many
- Substitute Drug by Active Substance entity
- Add active substance data from infarmed
- Remove administration options (just keep API)
- Delete automatic generation of Angular documentation
- Format HTML files using prettier
- Define specific sequences for each entity
- Feedback should be available in navbar only for User/Admin

Defects:
- Do not include parenthesis in therapeutic regime list and detail if the acronym is empty
- Remove notice from symptom list
- Fix routing when leaving creation/edition of a therapeutic regime
- User-management should be available in navbar only for Admin

Sonar:
- Master
image
- With this PR:
image

### CODE REVIEW

**Comment by sfdsilva** [comment]
"Add feedback and Active substance entities, and fields limits" is not in sprint. This PR needs to be closed.

**Review by aamarques — CHANGES_REQUESTED** [review]
Review the maxsize of Active susbstance Name. This could have 512 bytes as described in DB model here [https://www.infarmed.pt/documents/15786/2881335/CITS+-+Manual+Aplicacional+-+Webservices/a69a2a47-c455-59ca-ab57-bde198c9a82d]

  "name": "ActiveSubstance",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String",
      "javadoc": "Nome.",
      "fieldValidateRules": ["required", "maxlength"],
      "fieldValidateRulesMaxlength": "255"
    },

**Comment by DanielFran** [comment]
@aamarques Segui a documentação e tirei o tamanho desta tabela:
image

**Review by aamarques — COMMENTED** [review]
This is to stay in the code ? 
 "jwtSecretKey": "ODM4ODljNjAzYjkzZWY1ZDJkYjJlYTY5YzNkMWZmYWZhNDJjMDMzZmY...."

**Comment by DanielFran** [comment]
> 
> 
> This should to stay in the code ?
> "jwtSecretKey": "ODM4ODljNjAzYjkzZWY1ZDJkYjJlYTY5YzNkMWZmYWZhNDJjMDMzZmY...."

No. but until we do not have final servers where to configure it, we keep it here

**Comment by benjamim-ferreira** [comment]
My review was done only by interacting with the app. I run the application on my machine and tested it with manual_cypress 🤚🏽

**Comment by benjamim-ferreira** [comment]
this review (and the following ones) was done by installing the app and running it on my local machine. I do not look into the code, i only tested the funcionalities. For that, i used the "manual_cypress" (also know as my hand 🤚🏽 laying on my mouse). The issues that i dounded (together with @vkhsunny ) were:

1- 
  a) when creating the active substance (/active-substance/new) i was expecting a pop-up dialog, to prevent the user from losing all the information already inserted, when the button cancel is pressed. (to keep up with the other create forms)
  b) by looking to the creade medicine mock-up in figma's website, i can notice that:
  --> the "return" button (located in the left superior corner) is missing... i've inserted it on my "edit password and settings" feature...  we need to normalize this button because it is missing in several pages, or eliminate it if thats the case
  --> the form box has a length bigger than the mock-ups
  --> (this one i dont know if it was supposed to be implemented in this PR) the observations field is not accomplished (multiple forms)
  
  
  
image


  @sfdsilva @DanielFran

**Comment by DanielFran** [comment]
@benjamim-ferreira The active substance feature is exactly how is the Drug actually, so all you described are features that already defined to improve this functionality.

Example: 
image

**Comment by benjamim-ferreira** [comment]
2-

a) when i tried to create a new active substance i got the same error all the time (internal issue on the server) is something related with my local running or with the app? (please watch the print bellow)
b) 
--> in the dropdown form (type of administração) the field starts empty... i think it should start with a "please choose your option or ..." please verify this
--> also in the dropdown form, when trying it on a ipad pro, as you can see in the screenshoot, is not responsive  (watch the print bellow)

image

image

**Comment by DanielFran** [comment]
> 
> 
> 2-
> 
> a) when i tried to create a new active substance i got the same error all the time (internal issue on the server) is something related with my local running or with the app? (please watch the print bellow)
> b)
> --> in the dropdown form (type of administração) the field starts empty... i think it should start with a "please choose your option or ..." please verify this
> --> also in the dropdown form, when trying it on a ipad pro, as you can see in the screenshoot, is not responsive (watch the print bellow)
> 
> image
> 
@benjamim-ferreira 
a) Will investigate if I have same issue
b) The 'empty' value is normal because Administration Type is not anymore mandatory, so the empty is for the null value.

**Comment by andrenns** [comment]
> SonarCloud Quality Gate failed.
> 
> [Bug](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=CODE_SMELL) [29 Code Smells](https://sonarcloud.io/project/issues?id=MSE-2019-2021_support_care&pullRequest=73&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=MSE-2019-2021_support_care&pullRequest=73&metric=new_coverage&view=list) [76.3% Coverage](https://sonarcloud.io/component_measures?id=MSE-2019-2021_support_care&pullRequest=73&metric=new_coverage&view=list)
> [](https://sonarcloud.io/component_measures?id=MSE-2019-2021_support_care&pullRequest=73&metric=new_duplicated_lines_density&view=list) [1.3% Duplication](https://sonarcloud.io/component_measures?id=MSE-2019-2021_support_care&pullRequest=73&metric=new_duplicated_lines_density&view=list)

shouldn't test coverage be at least 80%?

**Review by andrenns — APPROVED** [review]
From my side, I don't see anything strange in the code
Just a suggestion for next big updates like this, DB schemas should be present before applying the changes on the code

**Comment by DanielFran** [comment]
> 
> 
> From my side, I don't see anything strange in the code
> Just a suggestion for next big updates like this, DB schemas should be present before applying the changes on the code

@andrenns 
image

**Pull request merged**
