### PR TITLE
MSEDO-227: [feat] Add login page

### PR DESCRIPTION
**Pull request by sfdsilva**
Related with feature MSEDO-174
Screen Shot 2020-12-01 at 18 05 00

### CODE REVIEW

**Comment by sfdsilva** [comment]
Screen Shot 2020-12-01 at 18 05 00

**Review by DanielFran — APPROVED** [review]
LGTM

**Review by DanielFran — CHANGES_REQUESTED** [review]
Rename login.scss to login.component.scss

**Comment by sfdsilva** [comment]
Will leave `login.scss` as is since all files match with the rule applied.

**Pull request merged**
