### PR TITLE
MSEDO-395: Fix some sonar warnings and update dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
Current Sonar statistics:
imagem

**Comment by DanielFran** [comment]
With current fixes:
imagem

**Comment by DanielFran** [comment]
Posso pedir sim

**Review by xalves — APPROVED** [review]
QA Approved the current coverage.

**Review by andrenns — APPROVED** [review]

**Pull request merged**
